server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///1906shop?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123

  redis:
    host: 192.168.199.199
    jedis:
      pool:
        max-active: 1000
        max-idle: 1000
        min-idle: 0